### PR TITLE
Updated README file

### PR DESCRIPTION
**Pull request by vaibhavshiledar**
Updated README file

### CODE REVIEW

**Comment by sammyd** [comment]
Hi @vaibhavshiledar, how are you getting on? I can see that you've started to follow the beginning git video course, but haven't completed it. Is that on purpose, or are you struggling?

**Comment by vaibhavshiledar** [comment]
Hello sir, 
 I just looking in free time i want just learn new things only😊

**Review by vaibhavshiledar — COMMENTED** [review]
Good change

**Comment by vaibhavshiledar** [comment]
Leave it

**Pull request closed without merging**
